version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: base-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3303:3306'
  cache:
    container_name: base-redis
    image: redis:6.2-alpine
    restart: always
    ports:
     - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  app:
      build: .
      container_name: base-app
      ports:
      - '8000:8000'
      restart: always
      volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
      depends_on:
        - db
        - cache
  # mailhog:
  #   image: mailhog/mailhog
  #   logging:
  #     driver: 'none'  # disable saving logs
  #   ports:
  #     - 1025:1025 # smtp server
  #     - 8025:8025 # web ui
  # cache:
volumes:
  mysql-data:
  cache:
    driver: local