version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3303:3306'
  app:
      build: .
      container_name: base-app
      ports:
      - '8000:8000'
      restart: always
      volumes:
      - .:/hoaNK/src/app
      depends_on:
        - db
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  mysql-data: