version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: base-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3303:3306'
  app:
      build: .
      container_name: base-app
      ports:
      - '8000:8000'
      restart: always
      volumes:
      - .:/hoaNK/src/app
      depends_on:
        - db
volumes:
  mysql-data: